name: Owen Chase
description: Graduate student in Astronomy at the University of Texas at Austin
author: Owen Chase
author_email: ochase10@gmail.com
google_analytics: G-3LL6Q0HLCS
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
